### ISSUE TITLE
Compilation error on linux due to inconsistent casing

### ISSUE THREAD

**Issue by thinkbeforecoding** [jnm2/ReferenceAssemblies.net35#3]
dotnet on linux cannot resolve framework assemblies when the casing of the dll file is not the same as the Assembly name.
Unfortunately, in net20 and net35, System.Configuration and System.Xml assemblies are located in dlls named System.configuration and System.XML.

**Comment by jnm2** [comment]
Reopening to track specific tests now that #4 is implemented.

**Comment by jnm2** [comment]
Verified that a test is already in place now that CI runs on Ubuntu: https://github.com/jnm2/ReferenceAssemblies.net35/runs/396133226

**Comment by thinkbeforecoding** [comment]
Thank you very much !!

Do you have a date in mind for the nuget ?

**Comment by jnm2** [comment]
I was hoping to get the other issue in https://github.com/jnm2/ReferenceAssemblies.net35/milestone/1 done first, but if that takes too long, I can publish without it. Is the 27th too far away?

**Comment by thinkbeforecoding** [comment]
No problem, I use an internal nuget feed for now :) so take your time

**Comment by jnm2** [comment]
I won't have time to get the other issue completed, so I uploaded 1.0.1 containing your fix. Thanks again!

https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35/1.0.1

**Comment by jnm2** [comment]
@thinkbeforecoding https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net35 has been published and is included in https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies, so this package is now obsolete.
